added checkbox
martonvolosin/erasmus-pokeapp pull request #2
Opened 2021-09-28 13:01 UTC by jijipurokoppu

2021-09-28 13:12 UTC, martonvolosin requested changes

2021-09-28 13:12 UTC, martonvolosin commented on src/components/FilterComponents/checkbox/CheckBox.js
> +function CheckBox () {
you will need an onchange callback added in props and bind it to the inputs onchange method.

2021-09-28 13:12 UTC, martonvolosin commented on src/screens/HomePage/homepage.js
> +     <div>
you can use React fragment instead of the divs if you dont add any class or prop to the div.

https://reactjs.org/docs/fragments.html#short-syntax

2021-09-29 08:41 UTC, MartinCechh approved these changes

2021-09-29 08:41 UTC, merged